### ISSUE TITLE
Agent code not found

### ISSUE THREAD

**Issue by oubiwann** [clojang/clojang#26]
With the new separation (and potentially other recent changes) of Agent from Clojang and jiface, the agent does not start successfully when Clojang starts:

```
$ lein repl
Exception in thread "main" java.lang.ClassNotFoundException: clojang.agent.startup
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:300)
    at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)
FATAL ERROR in native method: processing of -javaagent failed
Exception in thread "Thread-3" clojure.lang.ExceptionInfo: Subprocess failed {:exit-code 134}
    at clojure.core$ex_info.invoke(core.clj:4593)
    at leiningen.core.eval$fn__5830.invoke(eval.clj:255)
    at clojure.lang.MultiFn.invoke(MultiFn.java:233)
    at leiningen.core.eval$eval_in_project.invoke(eval.clj:356)
    at leiningen.repl$server$fn__11848.invoke(repl.clj:243)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.core$apply.invoke(core.clj:630)
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invoke(core.clj:634)
    at clojure.core$bound_fn_STAR_$fn__4439.doInvoke(core.clj:1890)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by oubiwann** [comment]
Oh, nice -- didn't know about this: to assist in debugging, I added ``"-verbose:class"`` to the ``project.clj``'s ``:jvm-opts``.

**Comment by oubiwann** [comment]
Okay, it turned out that ``:aot :all`` was needed at the top-level of the project for the agent to work when included in Clojang.

Fixes https://github.com/clojang/agent/issues/2

**Comment by oubiwann** [comment]
This has reared its head again ...

**Comment by oubiwann** [comment]
After the logging cleanups I mentioned above we made, I re-enabled them in the agent and no errors were thrown. It's still not clear the exact thing that cleared this up, but it do believe it was a JAR file conflict that was triggered either by old tertiary deps in the logging libs or the old Clojure jar that was getting pulled in. (Not directly, of course, rather I suspect there was an AOT'ed lib that was causing the issues ...)

Despite not having an exact solution, the agent is now working again, for the first time in a year. Definite success.
